### ISSUE TITLE
Error while getting AEPIdentity getExperienceCloudId on iOS devices

### ISSUE THREAD

**Issue by HudsonProenca-sf** [adobe/aepsdk-core-ios#1006]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-edge-ios/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [ ] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

While trying to get the `getExperienceCloudId` from the AEPIdentity library we are seeing a `com.adobe.marketing.mobile error 1` and also `AEPCore.AEPError error 1` errors

### Environment

Only happens on iOS devices.
SDK:  AEPIdentity 4.1.0
AEPCore: 4.1.0

### Steps to reproduce

I couldn't reproduce the error - we've been seeing this issue in Sentry - no one could reproduce it yet 

### Expected behavior

We wanna understand what this error means, we didn't find any information online. We wanna see if this is something fixable or if we should stop reporting it as an error.

### Anything else?

Here's a code snippet to give more context:

```dart
Identity.getExperienceCloudId(completion: { (experienceCloudId: String?, error: Error?) in
            DispatchQueue.main.async {
                if (experienceCloudId != nil) {
                    result(experienceCloudId);
                } else {
                    result(FlutterError.init(
                        code: "Error message",
                        message: error?.localizedDescription ?? "Unknown error",
                        details: nil
                    ));
                }
            }
        })
```

**Comment by cdhoffmann** [comment]
@HudsonProenca-sf Thanks for the detailed description. AEPError 1 is a timeout error. I have logged a ticket to update our public docs with this info but for now, you can look at our code [here](https://github.com/adobe/aepsdk-core-ios/blob/main/AEPCore/Sources/eventhub/AEPError.swift). This commonly happens when the API is called before you have a valid [configuration](https://developer.adobe.com/client-sdks/home/base/mobile-core/configuration/). You can either 1. Refactor to make sure you only call the API after you have downloaded a valid configuration, or 2. [Bundle a local configuration](https://developer.adobe.com/client-sdks/home/base/mobile-core/configuration/#using-a-bundled-file-configuration) file so that its always there.

**Comment by cdhoffmann** [comment]
Closing. Let us know if there are any other questions or concerns and we can discuss here.
