### ISSUE TITLE
Fortify scan issues

### ISSUE THREAD

**Issue by spraveenk91** [adobe/aepsdk-core-ios#1060]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-edge-ios/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

I am using Adobe Analytics through Cocoapods in my project, version details mentioned below:

> pod 'AEPCore', '4.2.0'
> pod 'AEPLifecycle', '4.2.0'
> pod 'AEPIdentity', '4.2.0'
> pod 'AEPAnalytics', '4.0.0'

We have [Fortify Static Code Analyzer](https://www.opentext.com/products/fortify-static-code-analyzer) integrated to our application and it has pointed several issues as mentioned below in different categories:

### Insecure Transport: Weak SSL Protocol

Not using TLS version 1.2 or above version caused this issue in below places

1. Pods/AEPServices/AEPServices/Sources/network/NetworkService.swift - Line no: 59

----

### Insecure Storage: Lacking Data Protection

Not using the right file protection in below places

1. Pods/AEPServices/AEPServices/Sources/storage/FileSystemNamedCollection.swift - Line no: 136
2. Pods/AEPServices/AEPServices/Sources/cache/DiskCacheService.swift - Line no: 30
3. Pods/AEPServices/AEPServices/Sources/storage/FileSystemNamedCollection.swift - Line no: 51
4. Pods/AEPServices/AEPServices/Sources/storage/FileSystemNamedCollection.swift - Line no: 80
5. Pods/AEPServices/AEPServices/Sources/ui/fullscreen/FullscreenMessage.swift - Line no: 146

----

### JSON Injection

1. Pods/AEPCore/AEPCore/Sources/migration/V5Migrator.swift - Line no: 66

----

Do adobe have any plans to fix them in near future to overcome these issues?

### Environment

* OS: 13.0 and above

* SDK(s): 
> 'AEPCore', '4.2.0'
> 'AEPLifecycle', '4.2.0'
> 'AEPIdentity', '4.2.0'
> 'AEPAnalytics', '4.0.0'

* IDE: XCode 15.2

### Steps to reproduce

Run the library using Fortify static code analyzer tool.

**Comment by cdhoffmann** [comment]
@spraveenk91 
We treat static code analyzer tool complaints as enhancement requests. That being said, these are requests we have seen before and here is our response to each: 

1. Insecure transport: We limit our network service to using https, but the network service can be overridden to provide your own custom implementation if you want to limit network traffic to TLS version 1.2 or above. See docs here: https://developer.adobe.com/client-sdks/home/base/mobile-core/platform-services/network-service/#overriding-networkservice
2. Insecure storage: We do not store any PII data in the SDK. We are not encrypting any of the data otherwise and that is by design.
3. JSON Injection: The data which is stored in JSON is grabbed from our servers OR stored locally. This means that our servers would need to be compromised, or the App bundle would need to be compromised (jailbroken). In which case, there is little we could do to stop an attacker. Also, the data stored in JSON is mostly configuration and other internal SDK data, no PII is stored here.

If there are still concerns, please reach out to PM to discuss feature requests.
