### ISSUE TITLE
Explorer better way to define AEPError

### ISSUE THREAD

**Issue by shalehaha** [adobe/aepsdk-core-ios#448]
the current `AEPError` is not extensible, extensions could not define a new error for themselves.

**Comment by nporter-adbe** [comment]
This is just my quick take on this.

I'm not aware of a good way to extend an existing error in Swift, my opinion would be to rename AEPError to AEPCoreError, then we could set the pattern that each extension can define their own errors something like AEPEdgeError, AEPIdentityError, so that we at least set a pattern that is extensible.

**Comment by shalehaha** [comment]
@nporter-adbe 
yes, hard to find a perfect solution. 
So currently I'm thinking we can just add more cases to AEPError, hopefully, to cover most of the use cases.

And for public API, to better fit into the normal practice of Swfit/Objc, we should return an optional `Error`.
So  change `static func appendTo(url: URL?, completion: @escaping (URL?, AEPError) -> Void) {` to `static func appendTo(url: URL?, completion: @escaping (URL?, Error?) -> Void) {`

cc @yangyansong-adbe
