### ISSUE TITLE
ServiceProvider.shared.loggingService cannot be overridden

### ISSUE THREAD

**Issue by m0rk** [adobe/aepsdk-core-ios#874]
### Prerequisites

- [X] This is not a Security Disclosure, otherwise please follow the guidelines in [Security Policy](https://github.com/adobe/aepsdk-edge-ios/security/policy).
- [X] I have searched in this repository's issues to see if it has already been reported.
- [X] I have updated to the latest released version of the SDK and the issue still persists.

### Bug summary

According to the [documentation](https://github.com/adobe/aepsdk-core-ios/tree/main/Documentation/Services#overriding-a-service) it should be possible to override the logging service, but the [implementation](https://github.com/adobe/aepsdk-core-ios/blob/main/AEPServices/Sources/ServiceProvider.swift#L101-L105) is a get-only property.

### Environment

* OS: iOS 16.1
* SDK(s): AEPCore 3.7.3
* IDE: Xcode 14.1

**Comment by cdhoffmann** [comment]
@m0rk It is actually intentional for the logging service to not be overridable. We do not want customers overriding it because we need our logs when helping them track down issues. The documentation is misleading though. We will make sure and update the documentation to not use the logging service as an example for overriding. Thank you.
